name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  crates:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rust
        uses: hecrj/setup-rust-action@master
        with:
          rust-version: stable
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish to crates.io
        run: |
          cargo login ${{secrets.CRATES_KEY}}
          cargo publish
